#!/usr/bin/env python3

read = """
{real} DgStreamRead{easy}(DgStream *context, DgError *error) {
	/**
	 * Read a {real} from the stream
	 * 
	 * @param context Stream to read from
	 * @param error Any error which occured will be stored here, may be NULL
	 * @return The {real} which was read from the stream
	 */
	
	{real} data;
	
	DgError error_code = DgStreamRead(context, sizeof data, &data);
	
	if (error_code) {
		if (error) {
			*error = error_code;
		}
		
		return {default};
	}
	
	if (DgStreamIsSwappingEndian(context)) {
		DgMemorySwapEndian(&data, sizeof data);
	}
	
	return data;
}

"""

read_decl = "{real} DgStreamRead{easy}(DgStream *context, DgError *error);\n"

write = """
DgError DgStreamWrite{easy}(DgStream *context, {real} data) {
	/**
	 * Write a {easy} to a stream.
	 * 
	 * @param context Stream object
	 * @param data The {easy} to write
	 * @return Error code
	 */
	 
	if (DgStreamIsSwappingEndian(context)) {
		DgMemorySwapEndian(&data, sizeof data);
	}
	
	return DgStreamWrite(context, sizeof data, &data);
}

"""

write_decl = "DgError DgStreamWrite{easy}(DgStream *context, {real} data);\n"

types_and_names = [
	["Int8", "int8_t", "0"],
	["UInt8", "uint8_t", "0"],
	["Int16", "int16_t", "0"],
	["UInt16", "uint16_t", "0"],
	["Int32", "int32_t", "0"],
	["UInt32", "uint32_t", "0"],
	["Int64", "int64_t", "0"],
	["UInt64", "uint64_t", "0"],
	["Float32", "float", "0.0f"],
	["Float64", "double", "0.0"],
]

c = open("stream_generated.c.part", "w")
h = open("stream_generated.h.part", "w")

c.write("// Auto-generated by generate_serialise_for_types.py\n")
c.write("// Reads\n")
for t in types_and_names:
	c.write(read.replace("{easy}", t[0]).replace("{real}", t[1]).replace("{default}", t[2]))

c.write("// Writes\n")
for t in types_and_names:
	c.write(write.replace("{easy}", t[0]).replace("{real}", t[1]).replace("{default}", t[2]))

h.write("// Auto-generated by generate_serialise_for_types.py\n")
h.write("// Reads\n")
for t in types_and_names:
	h.write(read_decl.replace("{easy}", t[0]).replace("{real}", t[1]).replace("{default}", t[2]))

h.write("// Writes\n")
for t in types_and_names:
	h.write(write_decl.replace("{easy}", t[0]).replace("{real}", t[1]).replace("{default}", t[2]))

c.close()
h.close()
