// Auto-generated by generate_serialise_for_types.py
// Reads
DgError DgStreamReadInt8(DgStream *context, int8_t* data);
DgError DgStreamReadUInt8(DgStream *context, uint8_t* data);
DgError DgStreamReadInt16(DgStream *context, int16_t* data);
DgError DgStreamReadUInt16(DgStream *context, uint16_t* data);
DgError DgStreamReadInt32(DgStream *context, int32_t* data);
DgError DgStreamReadUInt32(DgStream *context, uint32_t* data);
DgError DgStreamReadInt64(DgStream *context, int64_t* data);
DgError DgStreamReadUInt64(DgStream *context, uint64_t* data);
DgError DgStreamReadFloat32(DgStream *context, float* data);
DgError DgStreamReadFloat64(DgStream *context, double* data);
// Writes
DgError DgStreamWriteInt8(DgStream *context, int8_t data);
DgError DgStreamWriteUInt8(DgStream *context, uint8_t data);
DgError DgStreamWriteInt16(DgStream *context, int16_t data);
DgError DgStreamWriteUInt16(DgStream *context, uint16_t data);
DgError DgStreamWriteInt32(DgStream *context, int32_t data);
DgError DgStreamWriteUInt32(DgStream *context, uint32_t data);
DgError DgStreamWriteInt64(DgStream *context, int64_t data);
DgError DgStreamWriteUInt64(DgStream *context, uint64_t data);
DgError DgStreamWriteFloat32(DgStream *context, float data);
DgError DgStreamWriteFloat64(DgStream *context, double data);
